artifact_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1chme8ZpE7Ggjp1HEHGCuy4kIlHi74ThA/view?usp=sharing
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepareBaseModel
  base_model_path: artifacts/prepareBaseModel/base_model.h5
  updated_base_model_path: artifacts/prepareBaseModel/base_model_update.h5

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5

model_evaluation:
  root_dir: artifacts/model_evaluation
  model_evaluation_file_path: artifacts/model_evaluation/evaluation.txt